# Generated by Django 5.2.9 on 2025-12-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('text', models.TextField(verbose_name='Enunciado')),
                ('alternatives', models.JSONField(default=dict, verbose_name='Alternativas')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='Resposta Correta')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('banca', models.CharField(choices=[('FGV', 'FGV'), ('CEBRASPE', 'CEBRASPE'), ('FCC', 'FCC'), ('VUNESP', 'VUNESP'), ('IBFC', 'IBFC'), ('CESGRANRIO', 'CESGRANRIO'), ('CONSULPLAN', 'CONSULPLAN'), ('FUNDATEC', 'FUNDATEC'), ('OTHER', 'Outra')], db_index=True, max_length=100, verbose_name='Banca')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Ano')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('subject', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Disciplina')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto')),
                ('exam_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Prova')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-year', 'banca', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Ano')),
                ('banca', models.CharField(db_index=True, max_length=100, verbose_name='Banca')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nível')),
                ('page_url', models.URLField(max_length=500, verbose_name='URL da Página')),
                ('exam_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Prova')),
                ('answer_key_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Gabarito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('questions', models.ManyToManyField(blank=True, related_name='exams', to='questions.question')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
                'ordering': ['-year', 'banca'],
            },
        ),
    ]
